Table OngkosPekerja{
    id bigint [pk]
    id_produksi bigint [note: '''1. Ambil Data Mesin/Divisi/Dll''']
}

Table DetailOngkosSpindless{
    id bigint [pk]
    id_ongkos_spindless bigint [ref: > OngkosPekerja.id]
    id_produksi_rotary bigint [note: '''
        1. Ambil data mesin
        2. Ambil data tanggal 
        3. Ambil data ukuran
        4. Ambil data jenis kayu
        5. Ambil data kualitas (kw)
        6. Ambil data pekerja
        7. Ambil data keterangan
    ''']
    id_harga_pekerja bigint [ref: > HargaPekerja.id]
    id_total_solasi bigint [ref: > TotalSolasi.id]
    id_harga_solasi bigint [ref: > HargaSolasi.id]
    tanggal date
    banyak integer
    kubikasi float
    kubikasi_solasi float
    banyak_solasi integer
    ongkos_kubikasi float
    ongkos_mesin integer
    ongkos_kubikasi_mesin float
    ongkos_perlembar integer
}

Table TotalSolasi {
    id bigint [pk]
    total integer
}

Table HargaPekerja {
    id bigint [pk]
    harga integer
}

Table HargaSolasi {
    id bigint [pk]
    harga integer
}